# fly.toml app configuration file generated for rest-veterinaria on 2023-06-09T21:21:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rest-veterinaria"
primary_region = "mia"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
